db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: 123456
  volumes:
    - ./mysql-data:/var/lib/mysql
    - ./log/mysql:/var/log/mysql/
  ports:
    - "3306:3306"
webpacker:
  build: .
  command:  bash -c "rm -f tmp/cache/webpacker/.last-compilation-digest-development && bin/webpack-dev-server"
  volumes:
    - .:/app
  ports:
    - "3035:3035"
web:
  build: .
  command: bundle exec rails s -p 5001 -b '0.0.0.0'
  volumes:
    - .:/app
    # - ~/.ssh/id_rsa:/root/.ssh/id_rsa
  environment:
    - DOCKERIZED=true
  ports:
    - "5001:5001"
  links:
    - db
    - webpacker