# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 77adad07244cee59cd7df10083c3fe6ff26c83f2df331fb837ab5c91783a0229a69ee3f4b653d8a3e7f4416fc33c0b8ebb3b5971ca31281015d4aff0cc286534

test:
  secret_key_base: faa94312b6d31419f4f92ac3c118af957f12f94d76b2847a266f7795e19bfbe6e7e305e500f5a12e2a052514327a6019016dd099fb8bf55af07c285fa595901a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  # secret_key_base: edd40974a43dfede7401c03167c1a7ce544c39d6b083f3074f0a627007bc1639e1423e6b6fa94b088360fa48e70471f5bfb00b13993a0fd9f1c400fa201ec63d
